### ISSUE TITLE
The specified path is invalid.

### ISSUE THREAD

**Issue by tron777777** [xjabr/viral-clips-extractor#2]
D:\viral-clips-extractor>python clips_extractor.py --url https://www.youtube.com/watch?v=qgOsZ52zk5Q
The specified path is invalid.
The specified path is invalid.
Traceback (most recent call last):
  File "D:\viral-clips-extractor\clips_extractor.py", line 28, in <module>
    video_id, title, author = get_video(video_url, input_video)
  File "D:\viral-clips-extractor\core\utils\youtube.py", line 9, in get_video
    video.download(filename=filename)
  File "C:\Users\red\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\streams.py", line 312, in download
    with open(file_path, "wb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\viral-clips-extractor\\tmp/767F8aceFf4D00c1.mp4'

![image](https://github.com/xjabr/viral-clips-extractor/assets/162063441/2d907346-cdea-464b-8414-1049544c8907)

Followed all the steps to install. reqirement.txt got done no error messages.

**Comment by tron777777** [comment]
fixed it kinda, still get the "The specified path is invalid." 
I created a folder called tmp

**Comment by tron777777** [comment]
fixed it i missed installing ImageMagick.
